Site/WalkTheMaze/WalkTheMaze/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WalkTheMaze.Models;
using WalkTheMaze.DAL;

namespace WalkTheMaze.Controllers
{
    public class MapController : Controller
    {
        private GameContext db = new GameContext();

        //
        // GET: /Map/
        [Authorize]
        public ActionResult Index()
        {
            if (User.Identity.Name == "admin")
            {
                return View(db.Maps.ToList());
            }
            else
            {
                //var maps = db.Maps.Where(m => m.User.UserName == user || m.Public).Include(m => m.User);
                //var maps = db.Maps.Where(m => m.MapType.Public);
                var maps = db.Maps.Where(m => m.MapType == MapType.Public);
                return View(maps.ToList());
                

            }
        }

        //
        // GET: /Map/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            Map map = db.Maps.Find(id);
            if (map == null)
            {
                return HttpNotFound();
            }
            return View(map);
        }

        //
        // GET: /Map/Create
        [Authorize(Users = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Map/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Map map)
        {
            if (ModelState.IsValid)
            {
                db.Maps.Add(map);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(map);
        }

        //
        // GET: /Map/Edit/5
        [Authorize(Users = "admin")]
        public ActionResult Edit(int id = 0)
        {
            Map map = db.Maps.Find(id);
            if (map == null)
            {
                return HttpNotFound();
            }
            return View(map);
        }

        //
        // POST: /Map/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Map map)
        {
            if (ModelState.IsValid)
            {
                db.Entry(map).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(map);
        }

        //
        // GET: /Map/Delete/5
        [Authorize(Users = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Map map = db.Maps.Find(id);
            if (map == null)
            {
                return HttpNotFound();
            }
            return View(map);
        }

        //
        // POST: /Map/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Map map = db.Maps.Find(id);
            db.Maps.Remove(map);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Site/WalkTheMaze/WalkTheMaze/Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WalkTheMaze.Models;
using WalkTheMaze.DAL;

namespace WalkTheMaze.Controllers
{
    public class ScoreController : Controller
    {
        private GameContext db = new GameContext();

        //
        // GET: /Score/
        [Authorize]
        public ActionResult Index(int id = -1)
        {
            Map mapToView;
            List<Score> scores;

            if (id == -1) {
                mapToView = db.Maps.First();
            }
            else {
                mapToView = db.Maps.Find(id);
            }

            if (mapToView == null)
                return HttpNotFound();
            else
                scores = db.Scores.Include(s => s.Player)
                    .Include(s => s.Map)
                    .Where(m => m.MapID == mapToView.MapID)
                    .OrderByDescending(s => s.Points)
                    .ToList();
            ViewBag.maps = db.Maps.ToList();
            ViewBag.mapName = mapToView.MapName;
            return View(scores.ToList());
        }

        //
        // GET: /Score/Details/5
        [Authorize(Users = "admin")]
        public ActionResult Details(int id = 0)
        {
            Score score = db.Scores.Find(id);
            if (score == null)
            {
                return HttpNotFound();
            }
            return View(score);
        }

        //
        // GET: /Score/Create
        [Authorize(Users = "admin")]
        public ActionResult Create()
        {
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "Name");
            ViewBag.MapID = new SelectList(db.Maps, "MapID", "MapData");
            return View();
        }

        //
        // POST: /Score/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Score score)
        {
            if (ModelState.IsValid)
            {
                db.Scores.Add(score);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "Name", score.PlayerID);
            ViewBag.MapID = new SelectList(db.Maps, "MapID", "MapData", score.MapID);
            return View(score);
        }

        //
        // GET: /Score/Edit/5
        [Authorize(Users = "admin")]
        public ActionResult Edit(int id = 0)
        {
            Score score = db.Scores.Find(id);
            if (score == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "Name", score.PlayerID);
            ViewBag.MapID = new SelectList(db.Maps, "MapID", "MapData", score.MapID);
            return View(score);
        }

        //
        // POST: /Score/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Score score)
        {
            if (ModelState.IsValid)
            {
                db.Entry(score).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "Name", score.PlayerID);
            ViewBag.MapID = new SelectList(db.Maps, "MapID", "MapData", score.MapID);
            return View(score);
        }

        //
        // GET: /Score/Delete/5
        [Authorize(Users = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Score score = db.Scores.Find(id);
            if (score == null)
            {
                return HttpNotFound();
            }
            return View(score);
        }

        //
        // POST: /Score/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Score score = db.Scores.Find(id);
            db.Scores.Remove(score);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Site/WalkTheMaze/WalkTheMaze/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

        <script>
            function redirect(dropDownValue) {
                if (dropDownValue != null && dropDownValue.length > 0) {
                    window.location.href = document.URL + "?language=" + dropDownValue;
                }
            }
         </script>

    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title" style="color: #999">@Html.ActionLink("Walk The Maze", "Index", "Home")</p>
                </div>
                <div class="float-right">

                    <select name="lang" onchange="redirect(this.value)" style="float:right; margin-left:15px">
                        <option value="">@WalkTheMazeResources.Resource.SelectOne</option>
                        <option value="en-US">@WalkTheMazeResources.Resource.LangEN</option>
                        <option value="pt-PT">@WalkTheMazeResources.Resource.LangPT</option>
                    </select>
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink(@WalkTheMazeResources.Resource.Home, "Index", "Home")</li>
                            <li>@Html.ActionLink(@WalkTheMazeResources.Resource.About, "About", "Home")</li>
                            <li>@Html.ActionLink(@WalkTheMazeResources.Resource.Ldrbrds, "Index", "Score")</li>
                            <li>@Html.ActionLink(@WalkTheMazeResources.Resource.Map, "Index", "Map")</li>
                            <li>@Html.ActionLink(@WalkTheMazeResources.Resource.Contact, "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Walk The Maze</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>